export const topSongs = [
    {
        id: 1,
        title: "Stay",
        author: "The Kid LAROI, Justin Bieber",
        year: "2021",
        image: "stay.png",
        audio: "stay.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        lyrics: `I have one feeling (been dreaming) \n That you will finally come \n I have that feeling (been dreaming) \n And I know know that I'm rightOoh I wanna have that feelingOoh to be the only oneOoh \n I wanna have that feelingOoh to be the only one for youI have been waiting (praying) \n For you to finally showI have been waiting (praying) \n And I'm know that I'm rightBaby just for youI gotta vision of you`,
        personlikes: 672,
    },
    {
        id: 2,
        title: "Memories",
        author: "Marron 5",
        year: "2021",
        image: "memory.png",
        audio: "memory.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        lyrics: `I have one feeling (been dreaming) \n That you will finally come \n I have that feeling (been dreaming) \n And I know know that I'm rightOoh I wanna have that feelingOoh to be the only oneOoh \n I wanna have that feelingOoh to be the only one for youI have been waiting (praying) \n For you to finally showI have been waiting (praying) \n And I'm know that I'm rightBaby just for youI gotta vision of you`,
        personlikes: 672,
    },
    {
        id: 3,
        title: "Locked away",
        author: "R. City",
        year: " 2015",
        image: "lockaway.png",
        audio: "lockaway.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        lyrics: `I have one feeling (been dreaming) \n That you will finally come \n I have that feeling (been dreaming) \n And I know know that I'm rightOoh I wanna have that feelingOoh to be the only oneOoh \n I wanna have that feelingOoh to be the only one for youI have been waiting (praying) \n For you to finally showI have been waiting (praying) \n And I'm know that I'm rightBaby just for youI gotta vision of you`,
        personlikes: 672,
    },
    {
        id: 4,
        title: "Head In The Clouds",
        author: "Hayd",
        year: " 2015",
        image: "headincloud.png",
        audio: "headincloud.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        lyrics: `I have one feeling (been dreaming) \n That you will finally come \n I have that feeling (been dreaming) \n And I know know that I'm rightOoh I wanna have that feelingOoh to be the only oneOoh \n I wanna have that feelingOoh to be the only one for youI have been waiting (praying) \n For you to finally showI have been waiting (praying) \n And I'm know that I'm rightBaby just for youI gotta vision of you`,
        personlikes: 672,
    },
    {
        id: 5,
        title: "I'm Yours ",
        author: "Jason Mraz",
        year: " 2015",
        image: "imyour.png",
        audio: "imyour.mp3",
        releaseDate: "01/03/2024",
        providedBy: "JHOOM MUCSIC",
        lyrics: `I have one feeling (been dreaming) \n That you will finally come \n I have that feeling (been dreaming) \n And I know know that I'm rightOoh I wanna have that feelingOoh to be the only oneOoh \n I wanna have that feelingOoh to be the only one for youI have been waiting (praying) \n For you to finally showI have been waiting (praying) \n And I'm know that I'm rightBaby just for youI gotta vision of you`,
        personlikes: 672,
    },
];

export const albums = [
    {
        id: "1",
        image: "playlist1.jpg",
        title: "How I can say I love you",
        sub_title: "The art of music",
        date: "01/03/2024",
        creator: " Mathew",
        like: "30K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: "2",
        image: "playlist2.jpg",
        title: "Love you again",
        sub_title: "The amazing of music",
        date: "12/12/2022",
        creator: " Mathew",
        like: "60K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: "3",
        image: "playlist3.jpg",
        title: "Relaxing music",
        sub_title: "Music for soul",
        date: "12/12/2022",
        creator: " Mathew",
        like: "50K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
    {
        id: "4",
        image: "playlist4.jpg",
        title: "For the day",
        sub_title: "Good vide ",
        date: "12/12/2022",
        creator: " Mathew",
        like: "40K",
        imageArtist: "jason.jpg",
        artists_name: "Jackson",
    },
];

export const artists = [
    {
        id: "1",
        image: "justin.jpg",
        title: "Justin Bieber",
        sub_title: "The art of music",
    },
    {
        id: "2",
        image: "jason.jpg",
        title: "Jason Mraz",
        sub_title: "The art of music",
    },
    {
        id: "3",
        image: "rock.jpg",
        title: "R. City",
        sub_title: "The art of music",
    },
    {
        id: "4",
        image: "marron.jpg",
        title: "Marron 5",
        sub_title: "The art of music",
    },
];

export const songDeatail = [{}];
